language: node_js
node_js:
  - 0.4
  - 0.6
  - 0.7
before_script:
  - "mysql -uroot -e \"CREATE DATABASE IF NOT EXISTS test DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;\""
  - "mysql -uroot -e \"CREATE DATABASE IF NOT EXISTS test_denied DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;\""
  - "mysql -uroot -e \"GRANT ALL PRIVILEGES ON test.* TO 'test_user'@'localhost' IDENTIFIED BY '1234';\""
